##### MkDocs configuration #####

# Meta
site_name: 'JagTag-JS Documentation'
site_author: 'TheSharks'
site_url: 'http://thesharks.github.io/JagTag-JS'

# Repository configuration
repo_name: 'TheSharks/JagTag-JS'
repo_url: 'https://github.com/TheSharks/JagTag-JS'
edit_uri: 'edit/master/docs/'

# Copyright
copyright: 'Copyright © 2018 TheSharks. "Discord", "Discord App", and any associated logos are registered trademarks of Hammer & Chisel, inc.'

# Sitemap
pages:
  - Home: 'index.md'
  - Developers:
    - Introduction: 'developers/intro.md'
    - API: 'developers/api.md'
  - Users:
    - Introduction: 'users/intro.md'

# Theme
theme: 'material'

##### Material configuration #####

# Material features
extra:
  feature:
    tabs: true
  logo: 'img/settings.svg'
  palette:
    primary: 'indigo'
    accent: 'blue'
  font:
    text: 'Droid Sans'
    font: 'Droid Sans Mono'
  social:
    - type: 'github'
      link: 'https://github.com/TheSharks'

# Additional JavaScript
extra_javascript:
  - 'js/linkhelper.js'
  

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true 
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
