version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test & upload coverage data
          command: npm test
  npm-publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish
  gh-build:
    docker:
      - image: python:3.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Build
          command: |
            . venv/bin/activate
            mkdocs build
  gh-deploy:
    docker:
      - image: python:3.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Build
          command: |
            . venv/bin/activate
            mkdocs build
      - add_ssh_keys:
          fingerprints:
              - "90:a9:08:28:09:82:9e:a6:d7:b2:9e:aa:0b:85:6e:cc"
      - run:
          name: Deploy
          command: |
            . venv/bin/activate
            git config user.email 9768134+Dougley@users.noreply.github.com
            mkdocs gh-deploy

workflows:
  version: 2
  gh-pages:
    jobs:
      - gh-build
      - gh-deploy:
          requires:
              - gh-build
          filters:
            branches:
              only: master
  npm-publish:
    jobs:
        - test
        - npm-deploy:
            requires:
               - test
            filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*/
